### ISSUE TITLE
🐛「Bug」Can't handle Korean input correctly

### ISSUE THREAD

**Issue by octree** [simonbs/Runestone#11]
**Describe the bug**
Can't handle Korean input correctly

**Screenshots**

https://user-images.githubusercontent.com/7934444/166901295-93cb41aa-131d-4289-bab3-af121ad6d3c0.MOV

**Comment by simonbs** [comment]
@octree Thanks for reporting this issue and looking into it. I noticed that you had an open PR that you've recently closed. I assume it's because you're looking into alternative solutions.

The reason I'm calling `-selectionWillChange(_:)` and `-selectionDidChange(_:)` when editing is to move the caret to the next position when inserting a character. I think this is still necessary when editing Korean, but that we should be looking into Runestone's handling of _marked_ text.

Runestone supports editing multi stage input with UITextInput's concept of marked text, however, it may be that there's a bug.

**Comment by octree** [comment]
When inputting Korean, `setMarkedText` will not be called, but `replaceText` will be called.

Yes, I've opened a PR before that solves this issue, I can submit it again, I will be appreciate if you can help improve it.

**Comment by octree** [comment]
I found some documentation about `UITextInputDelegate `

> The text view also maintains references to a tokenizer and an input delegate. The text view calls methods declared by the UITextInputDelegate protocol to notify a system-provided input delegate about `external` changes in text and selection.

And some information from stackoverflow

> The methods of UITextInputDelegate are methods for your UITextInput-conforming responder to call on your `.inputDelegate` to inform it that you have changed your text or selection via means **other than keyboard input**.

We may should not call theses methods while the system updates the  `textSelectionRange`

**Comment by simonbs** [comment]
@octree Interesting! I never noticed that part of the documentation. I'll make sure to take a closer look at it and see if there are any changes necessary.

I have quite a few things I need to take care of after the launch, so I can't promise when I'll get around to this but it's high on my todo list.

**Comment by octree** [comment]
@simonbs I found here

[Lower Level Text Handling Technologies](https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/LowerLevelText-HandlingTechnologies/LowerLevelText-HandlingTechnologies.html#//apple_ref/doc/uid/TP40009542-CH15-SW23)

**Comment by octree** [comment]
LGTM, Great Job.

**Comment by simonbs** [comment]
@octree Great! Thanks for checking and for your assistance solving this bug. Closing the issue since #33 is merged.
