### ISSUE TITLE
Minimum Gutter Width Option

### ISSUE THREAD

**Issue by zachgibson** [simonbs/Runestone#110]
It'd be great to have an option on gutter layout to specify a minimum width. Specifically to solve the text view "jumping" when hitting double (or more) digits. This would be especially nice if code is less than 3 digits.

![repro](https://user-images.githubusercontent.com/10658888/177193986-6da23576-a8bb-4534-9260-8dc8895ad5ea.gif)

**Comment by simonbs** [comment]
@zachgibson  This sounds like a good idea. Would it make sense to have the minimum width specified in terms of a minimum amount of characters that the gutter should accompany rather than a pixel width? That way the minimum width can be set to contain, for example, three characters, and as such, the width won't change until the file reaches line 1000.

It's difficult coming up with a great name for the property holding this setting but I'm thinking of something along the liens of this:

```swift
textView.minimumGutterWidthCharacterCount = 3
```

**Comment by zachgibson** [comment]
Yeah I think that would work for majority of use-cases. Is there a reason you might not want to just expose the full frame dimensions?

**Comment by zachgibson** [comment]
Thanks @mmackh and @simonbs!
