### ISSUE TITLE
Go to line doesn't reveal line into view when keyboard is visible

### ISSUE THREAD

**Issue by rebornix** [simonbs/Runestone#112]
**Describe the bug**
Go to line doesn't scroll the line into safe area when virtual keyboard is visible

**To Reproduce**
* Open Example project
* In `MainViewController`, add a new action which always runs `self?.contentView.textView.goToLine(50)`
* Debug
* Open a document which contains more than 50 lines, scroll to the very top of the document
* Run the action
* Line 50 is revealed to the bottom of the viewport but it's covered by the visible virtual keyboard

**Expected behavior**
Line 50 should be above the keyboard

**Screenshots**

<img width="446" alt="image" src="https://user-images.githubusercontent.com/876920/178123503-9229edd9-a9bd-4ac7-a95b-e4a70c041d50.png">

---

Lastly thank you for the project, it reminds me of Codemirror and TextMate, both kind of become de factor standard on their own platform.

**Comment by rebornix** [comment]
This might not be a `bug` if `automaticScrollInset` is required to be updated by wrapper view.

**Comment by simonbs** [comment]
@rebornix Thanks for filing the issue. I've had a look at the issue and was able to reproduce it in the example project.

However, what you're are seeing is _mostly_ expected behavior. As you note, developers are expected to implement assign a meaningful value to automaticScrollInset in order to address this. A standard UITextView doesn't seem to automatically make room for the keyboard by adjusting its content insets, and as such, I decided that Runestone's TextView shouldn't do it either.

PRs #113 and #116 updates the example project to show how the content inset should be updated to accommodate the keyboard.

While reproducing the behavior described in this issue, I did find two bugs related to navigating to a specific line. Those are fixed in #114 and #115.

I'll close the issue for now but please don hesitate to reopen it if you believe there's still a bug or the implemented behavior is undesired.

**Comment by rebornix** [comment]
@simonbs thanks for the quick turnaround, the update example works pretty well. Also do you have a place where we can send feature requests for the Runestone iOS app (not this framework)?
