### ISSUE TITLE
SSH and Git Support

### ISSUE THREAD

**Issue by bladecoates** [simonbs/Runestone#131]
Loving the application. I periodically try to use my iPad as an on the go development machine. I try different IDE's trying to find on that fit and a lot leave much to be desired. I believe you have a winner here. The options, layout and current language support is on par with what I need.

Only thing I would need for my work flow to be complete is ssh and git/scm support. The creator of working copy also has a ssh application now. Might be worth it to reach out and see what kinda of integration options he's be interested in. I know he supports xcallback, and does a at least one text editor linked to under his app integration page. If he's willing, that'll knock out these two feature's. As I have yet to find an application that works better then working copy for git on the phone and I'm already using his ssh app, and am liking it so far.

With apples recent changes for multitasking for iPadOS. I can see a lot more people considering an iPad as a on the go development machine. So having these two features in place, or on the roadmap would help with the success of the application.

**Comment by simonbs** [comment]
This issue seems related to Runestone (the app) rather than the framework of the same name, which this repository contains. There I’ll close the issue.

However, I appreciate the feedback and would love to understand it better. You mention that you’re using both Secure ShellFish and Working Copy but that you need some kind of integration between those apps and Runestone, which other text editors have.

Can I get you to send me an e-mail on Runestone’s support mail and elaborate on the specific integrations and features you’d like to see in Runestone?
