### ISSUE TITLE
Blocking UI on closing bracket deletion in medium size TS file

### ISSUE THREAD

**Issue by rebornix** [simonbs/Runestone#132]
**Describe the bug**

Tokenization can freeze the UI for seconds in medium size TypeScript file.

**To Reproduce**

* Open https://github.com/microsoft/vscode/blob/main/src/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase.ts in Runestone (from App Store)
* Delete closing bracket at [line 35](https://github.com/microsoft/vscode/blob/main/src/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase.ts)
* Delete line break
* Delete the last closing bracket at [line 34](https://github.com/microsoft/vscode/blob/main/src/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase.ts#L34)
* On iPhone 12 Pro above step can take a full second to finish

**Expected behavior**

Tokenization does not freeze the UI

**Additional context**

While this was tested against Runestone from App Store, I also did some profiling with the Example app and the blocking operations are syntax highlighting

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/876920/181878062-c452611c-1c81-46ea-9ab9-4bb44a19ba89.png">

Didn't dig into the code deep yet but a few ideas of how this can be improved

* Tokenize asynchronously (in background thread if possible or limit how many lines are tokenized in each frame)
* Early return when new line tokens are identical to the previous ones and skip following lines (not sure if this is valid with Tree Sitter)

**Comment by simonbs** [comment]
Thanks for reporting this issue and for the detailed steps to reproduce @rebornix! 🙏

The issue should be fixed in #134. A detailed explanation of the fix is included in the description of the issue. As a note, Runestone does perform syntax highlighting in the background when scrolling the document but will intentionally perform syntax highlighting on the main thread when editing the document.

The reason for performing syntax highlighting on the main thread is to avoid the text being incorrectly colored immediately after editing. I've found it to be fine to perform this operation on the main thread as Runestone will rehighlight only a small amount of text when editing. Naturally, you found a case where this wasn't true but that should be fixed now 😊
