### ISSUE TITLE
Add FR localization

### ISSUE THREAD

**Issue by W1W1-M** [simonbs/Runestone#146]
Hi @simonbs,
Great work on Rhinestone, the app is nice 💪 I'd be interested in setting up localization (if needed) and localizing it to French 🇫🇷 (my second tongue). If that's ok, I'll make a draft PR for this.
Regards

**Comment by simonbs** [comment]
@W1W1-M Thanks for opening this enhancement request. I'm a little uncertain if you're referring to Runestone _the app_ or Runestone the framework (My bad for naming the app and the framework the app 😅).

This repository is concerned with the framework rather than the app. While I'd love to eventually localize the Runestone app, I do not have any concrete plans to do so at this time, since I'm prioritizing other changes to the app.

There are only a few localizations in this repository, but you're more than welcome to open a PR that translates those to French.

**Comment by W1W1-M** [comment]
I think I was a little too quick in scanning the repo and assumed it was for the app 😓 that being said, I'll stick to my proposal and make a PR for the handful of strings anyway. Thanks for clearing this up.

**Comment by simonbs** [comment]
No worries, it's very confusing the the framework and the app are names the same.

Thanks for opening the PR! I'll merge it right away.
