### ISSUE TITLE
Scroll to bottom

### ISSUE THREAD

**Issue by Blankwonder** [simonbs/Runestone#177]
Hey.

Is there a standard way to scroll the text view to the bottom? UITextView has `scrollRangeToVisible`, so it can be done by `[_textView scrollRangeToVisible:NSMakeRange([_textView.text length], 0)]`.

I tried using UIScrollview's methods, but it seems it fails to calculate the correct offset.

```swift
private func scrollToBottom() {
    let bottomOffset = CGPoint(x: 0, y: self.textView!.contentSize.height - self.textView!.bounds.height + self.textView!.contentInset.bottom)
    self.textView?.setContentOffset(bottomOffset, animated: false)
}
```

**Comment by simonbs** [comment]
It is not recommended to rely on TextView's content size as the text view does not know it's actual content size until the entire text has been laid out and that doesn't happen until by far most of the text has been on the screen, which more or less means that the user will need to scroll to the bottom of the text view in order for the content size to be final.

It makes sense to add UITextView's `-scrollRangeToVisible(_:)` to TextView. In fact, the implementation of TextView's [-scroll(to:)](https://github.com/simonbs/Runestone/blob/main/Sources/Runestone/TextView/TextView.swift#L1088) function is quite close to the one of `scrollRangeToVisible(_:)`. However, `-scroll(to:)` isn't public as of writing this.

I'll have a look at polishing the implementation of `-scroll(to:)` and exposing it as `scrollRangeToVisible(_:)`.

**Comment by simonbs** [comment]
@Blankwonder I believe this is addressed by the changes in #197. Can you try out the changes and let me know if it fulfills your need?

**Comment by Blankwonder** [comment]
@simonbs Thanks for adding it. I just tried it with the code below. But it seems it failed to scroll to the bottom. Instead, it stopped at about 3/4 of the full content.

```
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)

        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            self.scrollToBottom()
        }
    }

    private func scrollToBottom() {
        self.textView!.scrollRangeToVisible(NSMakeRange(self.textView!.text.count - 1 , 1))
    }

```

**Comment by simonbs** [comment]
> But it seems it failed to scroll to the bottom. Instead, it stopped at about 3/4 of the full content.

@Blankwonder I suspect this may be due to asynchronous syntax highlighting.

Are you syntax highlighting the text and if so, is there any chance you can share the text you're testing with and the language you're using to syntax highlight it?

I'd like to reproduce the issue to understand what is going on.

**Comment by Blankwonder** [comment]
@simonbs You may try this file: https://www.dropbox.com/s/hdovv3o515b9ad4/2022-09-21-154520.log?dl=0

I use Runestone to present the log content.

**Comment by simonbs** [comment]
@Blankwonder Thanks for getting back with a sample file. I believe the issue is addressed in #198.

There was a bug where Runestone had not typeset the text at the end of the specified range, and as such it was unable to determine the correct content offset.

I have tested the changes with your example file but with no syntax highlighting and I seem to get expected results.

Would you mind testing again with the changes in #198?

**Comment by Blankwonder** [comment]
@simonbs I just confirmed it now works perfectly. Thanks.

**Comment by simonbs** [comment]
> @simonbs I just confirmed it now works perfectly. Thanks.

Thanks for testing and for your prompt reply! 🙏
