### ISSUE TITLE
String length conflation warning

### ISSUE THREAD

**Issue by haldun** [simonbs/Runestone#206]
In code scanning phase, CodeQL found an issue in `IndentController.swift` file line 71:

> This String.utf16 length is used in a String, but it may not be equivalent.

> Using a length value from an NSString in a String, or a count from a String in an NSString, may cause unexpected behavior including (in some cases) buffer overwrites. This is because certain unicode sequences are represented as one character in a String but as a sequence of multiple characters in an NSString. For example, a 'thumbs up' emoji with a skin tone modifier (👍🏿) is represented as U+1F44D (👍) then the modifier U+1F3FF.

**Comment by simonbs** [comment]
@haldun Thanks for opening the issue.

It _should_ be perfectly safe to perform the operation on line 71 in this case since we're checking if `lineString.hasPrefix(indentString)` on line 68. However, I understand that CodeQL is throwing the error.

The changes in PR #207 should address the warning. I'm not familiar with CodeQL and haven't looked into how I can set it up for a Swift project, so I have not validated these changes with CodeQL.

Is there any chance you can run the changes in PR #207 through CodeQL and see if the result matches your expectations?

**Comment by simonbs** [comment]
No worries! Glad to hear it's resolved now.
