### ISSUE TITLE
Undo & Redo with Runeestone App

### ISSUE THREAD

**Issue by msaitow** [simonbs/Runestone#232]
Dear simonbs,

I would like to continue this thread as it seems impossible for me to reopen it: https://github.com/simonbs/Runestone/issues/224

I suppose you're talking about the Runestone framework but not the APP. What I wanna know is how to undo or redo in the Runestone App. Sorry if this is a stupid question.

Sincerely,
msaitow

**Comment by simonbs** [comment]
There are several ways to undo and redo in the app. You can use the arrow keys above the virtual keyboard, CMD + Z on a physical keyboard, the menu that's presented when three-finger tapping the text view, and you can shake the device.

I'll close this issue since this repository is concerned about the open-source framework rather than the app. For support regarding the app, please send an e-mail to mail at runestone dot app.

![IMG_F2829070DF3D-1](https://user-images.githubusercontent.com/830995/198945876-007e9650-d00c-42e7-8051-5f2524150375.jpeg)

![IMG_F1F09D6BC2F5-1](https://user-images.githubusercontent.com/830995/198945750-e47d0631-0011-4a47-ad40-05e0b83829e9.jpeg)
