### ISSUE TITLE
After upgrading TreeSitterLanguages from 0.1.6 to 0.1.7 markdown is not highlighted as expected any more

### ISSUE THREAD

**Issue by funkenstrahlen** [simonbs/Runestone#259]
### What happened?

In 0.2.12 with TreeSitterLanguages in 0.1.4 markdown bold text `**bold**` is parsed as `HighlightName.strong` in

```Swift
public func fontTraits(for rawHighlightName: String) -> FontTraits
```

This allows me to render the bold markdown text as expected.

However in 0.2.12 together with `TreeSitterLanguages` 0.1.7 the same input string in the text view is reported as `punctuation.special`.

Therefore the highlighting code im my theme does not work as expected any more.

### What are the steps to reproduce?

* Install Runestone 0.2.12 with TreeSitterLanguages 0.1.7
* Setup a TextView with TextViewState configured for `.markdown`.
* Provide a theme and implement `public func fontTraits(for rawHighlightName: String) -> FontTraits`
* Enter some text in the TextView with `**bold**` 

### What is the expected behavior?

The function in the theme `public func fontTraits(for rawHighlightName: String) -> FontTraits` does receive the `text.strong`.

**Comment by simonbs** [comment]
@funkenstrahlen 

Thanks for opening the issues and providing the steps to reproduce. However, I was unable to reproduce the issue with the steps listed. I just tested with Runestone 0.2.12 and TreeSitterLanguages 0.1.7 and I'm seeing `**bold**` being highlighted as `text.strong`.

Are there any details I could be missing in order to reproduce this? For example, does it only happen when testing with certain files?

<img width="500" alt="Screenshot 2023-01-18 at 14 45 22" src="https://user-images.githubusercontent.com/830995/213188239-a5ceb326-0b6e-4df4-b67c-01fc428db512.png">

**Comment by funkenstrahlen** [comment]
Thank you very much for spending your time and looking into this! ❤️ 

Unfortunate that you can not reproduce the issue.

I tried to track it down further.

Updating the Runestone package to from 0.1.10 to 0.2.12 does not cause the bug to appear in my code.

The relevant change that causes the issue in my code is updating TreeSitterLanguages from 0.1.6 to 0.1.7. As soon as I update this package to version 0.1.7 it breaks my markdown highlighting. 0.1.6 still works fine.

However I can not see any changes in this diff that look like they could cause the issue I am having.
https://github.com/simonbs/TreeSitterLanguages/compare/0.1.6...0.1.7 

Next I tried to check if it might be an issue with the language I initialise my `TextViewState` with.

It looks like this:

```swift
            let state = TextViewState(text: "", theme: MyCustomTheme(), language: .markdown)
            DispatchQueue.main.async { [weak self] in
                self?.textView.setState(state)
            }
```

Currently I use `TreeSitterMarkdown` which only detects `HighlighName.title` correctly.

Just to see what's happening I switched to `TreeSitterMarkdownInline` language for my TextView. Now every markdown element is detected correctly **except** `HighlightName.title`. So just the other way around from `TreeSitterMarkdown`. 🤔 

What is actually the difference between `TreeSitterMarkdownInline` and `TreeSitterMarkdown`. Why are there two versions?

I also tried to download the Runestone Example Code and adapt it to provide a reproducible example for you. However I can not get it to build (no changes after downloading current `main` from Github and opening `Example.xcodeproj`:

<img width="1258" alt="Screenshot 2023-01-18 at 16 00 29" src="https://user-images.githubusercontent.com/144173/213205575-3b3dd471-5017-4668-8da5-f84bb819c30e.png">

I do not know how to investigate this issue any further. Do you have any idea what I can do or what additional information I can provide?

**Comment by simonbs** [comment]
@funkenstrahlen Thanks for following up and posting your code snippet. After looking at that, I have a theory as to what is going on.

The [tree-sitter-markdown parser](https://github.com/MDeiml/tree-sitter-markdown) was recently split into two parsers: a parser for block structure and a parser for inline structure. This is explained [in the README in the tree-sitter-markdown repository](https://github.com/MDeiml/tree-sitter-markdown#structure). This means that it is necessary to perform two parses of the document and the parser now utilizes injected languages.

Fortunately, Runestone supports this but requires that you opt into it. When initializing your TextViewState, you must provide an instance of an object conforming to the TreeSitterLanguageProvider protocol.

```swift
let languageCatalog = LanguageCatalog()
TextViewState(text: text, theme: theme, language: .markdown, languageProvider: languageCatalog)
```

This object lets Runestone look up injected languages. A sample implementation is provided below.

```swift
final class LanguageCatalog: TreeSitterLanguageProvider {
  func treeSitterLanguage(named languageName: String) -> TreeSitterLanguage? {
    if languageName == "markdown" {
      return .markdown
    } else if languageName == "markdown_inline" {
      return .markdownInline
    } else {
      return nil
    }
  }
}
```

After the first parser pass, Runestone (Tree-sitter, really) will have identifier areas of the document that should be highlighted with the markdown-inline parser. In order to make a pass with that parser, Runestone will ask your instance of TreeSitterLanguageProvider to create and return the parser to be used. Unfortunately, this requires matching of languages by their string value and the best way to find these language names is to inspect the highlights.scm file used by a parser. I h have provided the names for the markdown parsers in the code snippet above.

This implementation is not provided by default as Runestone itself contains no references to any languages.

**Comment by funkenstrahlen** [comment]
Thank you so much for your incredible detailed explanation! I learned a lot from that.

Implementing the language provider actually fixed my issue! Now the markdown is parsed as expected.

You are doing amazing work here! Sending some hugs!
