### ISSUE TITLE
Renaming a file from the top dropdown "freezes" the app

### ISSUE THREAD

**Issue by fmt** [simonbs/Runestone#268]
### What happened?

Renaming doesn't change the filename text on the top bar, nor does "Done" closes the file.

The editor seems responsive but I cannot edit it's contents.

The only way to recover seems to be "killing" Runestone in the ... Close app or bringing another window into focus until iPadOS drops Runestone from memory; focusing back Runestone is back on the file list and the filename was correctly changed.

![screenshot](https://user-images.githubusercontent.com/140614/218060563-649b96ca-197c-48b9-b5e3-0fcb068c7512.png)

### What are the steps to reproduce?

1. Create a file, open it in the editor
2. Click the filename on the top bar and select rename
3. rename the file and press enter
4. the filename will not change to the new name and the app freezes, although the toolbar seems to work, the editor content scrolls (but doesn't edit) and the filename does change on the filesystem

### What is the expected behavior?

Runestone should change the filename displayed and continue nominal operation

**Comment by simonbs** [comment]
@fmt Thanks for reporting the issue. This repository contains the source code for the Runestone open-source framework, the core of the Runestone Text Editor app, and your issue seems to be concerned with the app rather than the framework. I've made a note of your issue and will look into it for a future update.
