### ISSUE TITLE
Edit hidden files

### ISSUE THREAD

**Issue by xcojonny** [simonbs/Runestone#282]
### What happened?

Using ShellFish to sync Data between my server and Runestone. Hidden files (e.g. `.env`) are not visible.

Or is it me being the problem? 🙄

Best regards

### What are the steps to reproduce?

Browse to folder with .env file inside.
Hidden files (e.g. `.env`) are not visible.

### What is the expected behavior?

Hidden files are visible
(Within Textastic these files are visible)

**Comment by simonbs** [comment]
Apple's Files app does not enable developers to show files starting with a dot. You may use Working Copy to access these files through its custom file provider.

This comment seems related to the Runestone app rather than the open-source framework which this repository contains. Therefore I will close the comment.
