### ISSUE TITLE
Feature Request: Add URI scheme support on both Mac and iOS, so files can opened in Runestone with URLs.

### ISSUE THREAD

**Issue by YousufSSyed** [simonbs/Runestone#293]
### Is your feature request related to a problem?

I'd like to be able to enter in URLs on my iOS devices to open files in Runestone.

### What solution would you like?

Runestone to support URI schemes, perhaps they could start with `runestone://`. A good example to look at is the Taio app which has documentations for URIs in its app: https://docs.taio.app/#/integration/url-schemes.

### What alternatives have you considered?

None.

**Comment by simonbs** [comment]
I do not have any concrete plans to support URL schemes in Runestone but may consider it for a future update. 

This issue seems to be a feature request for the Runestone app rather than the open-source framework which this repository contains. Feature requests can be sent to mail at runestone dot app. I will close the issue.
