### ISSUE TITLE
Can't edit hidden files

### ISSUE THREAD

**Issue by wolf** [simonbs/Runestone#42]
**Describe the bug**
A file whose name starts with a dot character or in a directory whose name starts with a dot character cannot be reached to open it for editing. 

**To Reproduce**
Use Working Copy to clone the typical dotfiles project, e.g., GitHub.com:wolf/dotfiles.git. Many scripts live inside bash/.bash_topics.d as you can see from Working Copy. You cannot reach these files from Runestone.

**Expected behavior**
Runestone should either show the hidden files by default or else provide a setting to make them visible.

**Comment by simonbs** [comment]
Thanks for your feedback. Apple's document browser, which Runestone uses to display and select files, doesn't support showing hidden files. I'm crossing my fingers that'll change in the future 🤞

This issue seems related to the Runestone app rather than the Runestone framework, so I'll close the issue for now. Don't hesitate to reach me on mail if you have any other feedback for the Runestone app.
