### ISSUE TITLE
insertText(...) does not update caret position in TextView

### ISSUE THREAD

**Issue by PasiSalenius** [simonbs/Runestone#79]
**Describe the bug**
Inserting characters to a `TextView` programmatically, for example from a keyboard input view with quick access special keys, seems to be done by calling `insertText(_ text: String)` method on `TextView`. This adds the characters and they appear, but the caret is not moved after the newly inserted characters but stays where it was, even though the implementation seems to attempt to move the caret.

Typing more characters using the native keyboard does move the caret after the new text. Also moving the caret using arrow keys does begin moving from the position where the caret was supposed to be. So it seems like the caret position (`selectedRange`?) has the correct value, but it is not reflected in the `TextView` after text insertion.

I also tried to move the caret programmatically, by adjusting `selectedRange`'s `location` property, but it results in the caret being moved too many steps ahead.

**To Reproduce**
- Call `textView.insertText("a")` on an existing `TextView` instance.
- New characters appear but the caret stays in the same location before the inserted characters.

**Expected behavior**
Caret should move to a position after the newly inserted characters.

**Comment by PasiSalenius** [comment]
Upon further inspection this seems to be a regression between 0.1.1 and current main branch.

**Comment by nighthawk** [comment]
I came across the same issue. It happens when programatically appending some text rather than through regular typing. 

It works fine if I add a call to `sendSelectionChangedToTextSelectionView()` into `TextInputView.replaceText(in:with:selectedRangeAfterUndo:undoActionName:)`, e.g., in between these two lines: https://github.com/simonbs/Runestone/blob/3e5d191217c479bc11f7920c5b3fb5f119908e93/Sources/Runestone/TextView/TextInput/TextInputView.swift#L1091-L1092

I am not sure if that's the proper fix for this, or if there's a better way though. @simonbs , can you help?

**Comment by simonbs** [comment]
Thanks for looking into this @PasiSalenius and @nighthawk. I haven't had time to look into this yet but it's high on my todo list. I'll follow up.

**Comment by simonbs** [comment]
Thanks for investigating the issue @PasiSalenius and @nighthawk, and thanks for suggesting a fix. I've applied your suggested fix in #86 but I have changed it slightly.

I'd prefer to only call `-sendSelectionChangedToTextSelectionView` when absolutely needed. In this case we'd like to handle the text being edited programmatically and have the selection change being reflected in the UI. We can handle the case of text being programmatically edited by hooking into the TextView rather than the TextInputView. UIKit will invoke the instance of UITextInput (in our case TextInputView) directly when editing text.

So I've decided to call `-sendSelectionChangedToTextSelectionView` from the instance of TextView. The solution isn't _that_ pretty because `-sendSelectionChangedToTextSelectionView` can no longer be private but it means that we aren't calling the function unnecessarily.
